//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="House", Namespace="http://schemas.datacontract.org/2004/07/HouseManagerService")]
    public partial class House : object
    {
        
        private HouseServiceReference.Address AddressField;
        
        private HouseServiceReference.ChatMessage[] ChatField;
        
        private HouseServiceReference.Chore[] ChoresField;
        
        private int IdField;
        
        private string InviteCodeField;
        
        private string NameField;
        
        private HouseServiceReference.PersonToHouse[] PeopleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HouseServiceReference.Address Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HouseServiceReference.ChatMessage[] Chat
        {
            get
            {
                return this.ChatField;
            }
            set
            {
                this.ChatField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HouseServiceReference.Chore[] Chores
        {
            get
            {
                return this.ChoresField;
            }
            set
            {
                this.ChoresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InviteCode
        {
            get
            {
                return this.InviteCodeField;
            }
            set
            {
                this.InviteCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HouseServiceReference.PersonToHouse[] People
        {
            get
            {
                return this.PeopleField;
            }
            set
            {
                this.PeopleField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Address", Namespace="http://schemas.datacontract.org/2004/07/HouseManagerService")]
    public partial class Address : object
    {
        
        private string CityField;
        
        private string DoorNoField;
        
        private short FloorNoField;
        
        private string HouseNoField;
        
        private int IdField;
        
        private string StreetField;
        
        private int ZipCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                this.CityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DoorNo
        {
            get
            {
                return this.DoorNoField;
            }
            set
            {
                this.DoorNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short FloorNo
        {
            get
            {
                return this.FloorNoField;
            }
            set
            {
                this.FloorNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HouseNo
        {
            get
            {
                return this.HouseNoField;
            }
            set
            {
                this.HouseNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Street
        {
            get
            {
                return this.StreetField;
            }
            set
            {
                this.StreetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ZipCode
        {
            get
            {
                return this.ZipCodeField;
            }
            set
            {
                this.ZipCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChatMessage", Namespace="http://schemas.datacontract.org/2004/07/HouseManagerService")]
    public partial class ChatMessage : object
    {
        
        private int IdField;
        
        private string MessageField;
        
        private System.DateTime SendDateField;
        
        private HouseServiceReference.Person SenderField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SendDate
        {
            get
            {
                return this.SendDateField;
            }
            set
            {
                this.SendDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HouseServiceReference.Person Sender
        {
            get
            {
                return this.SenderField;
            }
            set
            {
                this.SenderField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Chore", Namespace="http://schemas.datacontract.org/2004/07/HouseManagerService")]
    public partial class Chore : object
    {
        
        private string DescriptionField;
        
        private System.DateTime DueDateField;
        
        private int IdField;
        
        private HouseServiceReference.Person PersonField;
        
        private byte StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DueDate
        {
            get
            {
                return this.DueDateField;
            }
            set
            {
                this.DueDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HouseServiceReference.Person Person
        {
            get
            {
                return this.PersonField;
            }
            set
            {
                this.PersonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonToHouse", Namespace="http://schemas.datacontract.org/2004/07/HouseManagerService")]
    public partial class PersonToHouse : object
    {
        
        private bool IsOwnerField;
        
        private System.DateTime MoveInDateField;
        
        private System.Nullable<System.DateTime> MoveOutDateField;
        
        private HouseServiceReference.Person PersonField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsOwner
        {
            get
            {
                return this.IsOwnerField;
            }
            set
            {
                this.IsOwnerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime MoveInDate
        {
            get
            {
                return this.MoveInDateField;
            }
            set
            {
                this.MoveInDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> MoveOutDate
        {
            get
            {
                return this.MoveOutDateField;
            }
            set
            {
                this.MoveOutDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HouseServiceReference.Person Person
        {
            get
            {
                return this.PersonField;
            }
            set
            {
                this.PersonField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://schemas.datacontract.org/2004/07/HouseManagerService")]
    public partial class Person : object
    {
        
        private System.DateTime DateOfBirthField;
        
        private string EmailField;
        
        private string FirstNameField;
        
        private int IdField;
        
        private string LastNameField;
        
        private string PassWordField;
        
        private string PhoneField;
        
        private string UserNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateOfBirth
        {
            get
            {
                return this.DateOfBirthField;
            }
            set
            {
                this.DateOfBirthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PassWord
        {
            get
            {
                return this.PassWordField;
            }
            set
            {
                this.PassWordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone
        {
            get
            {
                return this.PhoneField;
            }
            set
            {
                this.PhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HouseServiceReference.IHouseService")]
    public interface IHouseService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHouseService/CreateHouse", ReplyAction="http://tempuri.org/IHouseService/CreateHouseResponse")]
        System.Threading.Tasks.Task<bool> CreateHouseAsync(HouseServiceReference.House house, string sessionid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHouseService/UpdateHouse", ReplyAction="http://tempuri.org/IHouseService/UpdateHouseResponse")]
        System.Threading.Tasks.Task<bool> UpdateHouseAsync(HouseServiceReference.House house, string sessionid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHouseService/GetAllHouse", ReplyAction="http://tempuri.org/IHouseService/GetAllHouseResponse")]
        System.Threading.Tasks.Task<HouseServiceReference.House[]> GetAllHouseAsync(string sessionid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHouseService/DeleteHouse", ReplyAction="http://tempuri.org/IHouseService/DeleteHouseResponse")]
        System.Threading.Tasks.Task<bool> DeleteHouseAsync(HouseServiceReference.House house, string sessionid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHouseService/JoinHouse", ReplyAction="http://tempuri.org/IHouseService/JoinHouseResponse")]
        System.Threading.Tasks.Task<bool> JoinHouseAsync(string invitecode, string sessionid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHouseService/LeaveHouse", ReplyAction="http://tempuri.org/IHouseService/LeaveHouseResponse")]
        System.Threading.Tasks.Task<bool> LeaveHouseAsync(HouseServiceReference.House house, string sessionid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IHouseServiceChannel : HouseServiceReference.IHouseService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class HouseServiceClient : System.ServiceModel.ClientBase<HouseServiceReference.IHouseService>, HouseServiceReference.IHouseService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public HouseServiceClient() : 
                base(HouseServiceClient.GetDefaultBinding(), HouseServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IHouseService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HouseServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(HouseServiceClient.GetBindingForEndpoint(endpointConfiguration), HouseServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HouseServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(HouseServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HouseServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(HouseServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HouseServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<bool> CreateHouseAsync(HouseServiceReference.House house, string sessionid)
        {
            return base.Channel.CreateHouseAsync(house, sessionid);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateHouseAsync(HouseServiceReference.House house, string sessionid)
        {
            return base.Channel.UpdateHouseAsync(house, sessionid);
        }
        
        public System.Threading.Tasks.Task<HouseServiceReference.House[]> GetAllHouseAsync(string sessionid)
        {
            return base.Channel.GetAllHouseAsync(sessionid);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteHouseAsync(HouseServiceReference.House house, string sessionid)
        {
            return base.Channel.DeleteHouseAsync(house, sessionid);
        }
        
        public System.Threading.Tasks.Task<bool> JoinHouseAsync(string invitecode, string sessionid)
        {
            return base.Channel.JoinHouseAsync(invitecode, sessionid);
        }
        
        public System.Threading.Tasks.Task<bool> LeaveHouseAsync(HouseServiceReference.House house, string sessionid)
        {
            return base.Channel.LeaveHouseAsync(house, sessionid);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IHouseService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IHouseService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8733/Design_Time_Addresses/HouseManagerService/HouseService/");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return HouseServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IHouseService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return HouseServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IHouseService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IHouseService,
        }
    }
}
